site_name: Spirit, Soul and Body 
pages:
    - Home: index.md
    - Composition: composition.md
    - Formation: formation.md
    - Architecture: architecture.md
    - Facts About Spirit: facts-about-spirit.md
theme: material